// export {};
var myString;
var myNum;
var myBool;
var myVal;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'abc';
myNum = 22;
myBool = true;
myVal = 5;
strArr = ['hello', 'world'];
numArr = [1, 2, 3];
boolArr = [true, false];
strNumTuple = ['Hello', 4];
// strNumTuple = ['Hello', 4, 3]; still works
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
console.log(myUndefined);
